apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-transaction-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "bank-api-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/data/bank/db"
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: bank-api
        image: ghcr.io/YOUR_USERNAME/enterprise-devsecops-github-demo:latest
        ports:
        - containerPort: 8080
