name: Enterprise DevSecOps Pipeline

on:
  push:
    branches: ["**"]
    tags: ["v*"]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python -m py_compile app.py

  dependency-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          exit-code: '0' # put value 1 if you want to fail the pipeline intensionally for HIGH CRITICAL severity 

  docker:
    runs-on: ubuntu-latest
    needs: dependency-scan
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  container-scan:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          severity: "HIGH,CRITICAL"
          exit-code: "0" # put value to 1 if want to fail the pipeline intentionally for HIGH CRITICAL severity
 
  cosign-sign:
    runs-on: ubuntu-latest
    needs: container-scan
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: sigstore/cosign-installer@v3
      - run: cosign sign --yes $IMAGE_NAME:$IMAGE_TAG

  deploy-dev:
    if: startsWith(github.ref, 'refs/heads/feature')
    runs-on: ubuntu-latest
    needs: cosign-sign
    environment: dev
    steps:
      - run: echo "Deploy to DEV via GitOps"

  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: cosign-sign
    environment: production
    steps:
      - run: echo "Manual Approval Required for Production"
